pipelines:
  tags:
      deploy-*:
        - step:
            name: Build and package
            script:
              - apt-get update && apt-get install -y zip
              - apt-get install -y python3-pip 
              - pip3 install -r requirements.txt --target ./package
              - cd package
              - zip -r9 ${OLDPWD}/Melget.zip .
              - cd $OLDPWD
              - zip -g Melget.zip *.py
            artifacts:
              - Melget.zip
        - step:
            name: Deploy
            deployment: Test
            script:
              - echo "This script runs only on deploy of $BITBUCKET_TAG"
              - pipe: atlassian/aws-s3-deploy:0.2.1
                variables:
                  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                  AWS_DEFAULT_REGION: 'us-east-1'
                  S3_BUCKET: "fcopuerto-deploy-cloudformation/lambdas/$BITBUCKET_BRANCH/"
                  LOCAL_PATH: "./"    
              - pipe: atlassian/aws-cloudformation-deploy:0.6.3
                variables:
                  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                  AWS_DEFAULT_REGION: 'us-east-1'
                  STACK_NAME: 'MELGet-Deploy-$BITBUCKET_BRANCH'
                  TEMPLATE: 'https://fcopuerto-deploy-cloudformation.s3.amazonaws.com/lambdas/$BITBUCKET_BRANCH/deploy_$BITBUCKET_BRANCH.yml'
                  CAPABILITIES: 
                    - "CAPABILITY_IAM"
                    - "CAPABILITY_NAMED_IAM"  
  branches:
    default:
    master:
      - step:
            name: Deploy
            deployment: Test
            script:
              - pipe: atlassian/aws-s3-deploy:0.2.1
                variables:
                  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                  AWS_DEFAULT_REGION: 'us-east-1'
                  S3_BUCKET: 'fcopuerto-deploy-cloudformation/lambdas/production'
                  LOCAL_PATH: "./"    
              - pipe: atlassian/aws-cloudformation-deploy:0.6.3
                variables:
                  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                  AWS_DEFAULT_REGION: 'us-east-1'
                  STACK_NAME: 'MELGet-Deploy'
                  TEMPLATE: 'https://fcopuerto-deploy-cloudformation.s3.amazonaws.com/lambdas/production/deploy.yml'
                  CAPABILITIES: 
                    - "CAPABILITY_IAM"
                    - "CAPABILITY_NAMED_IAM"    
    devel_culoss:
      - step:
            name: Build and package
            script:
              - apt-get update && apt-get install -y zip
              - apt-get install -y python3-pip 
              - pip3 install -r requirements.txt --target ./package
              - cd package
              - zip -r9 ${OLDPWD}/Melget.zip .
              - cd $OLDPWD
              - zip -g Melget.zip *.py
            artifacts:
              - Melget.zip
      - step:
            name: Update Lambda code by Branch
            script:
              - echo 'This script runs only on commits of the branch $BITBUCKET_BRANCH '
              - pipe: atlassian/aws-lambda-deploy:0.2.1
                variables:
                  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                  AWS_DEFAULT_REGION: 'us-east-1'
                  FUNCTION_NAME: 'MELGet-$BITBUCKET_BRANCH'
                  COMMAND: 'update'
                  ZIP_FILE: 'Melget.zip'
                