pipelines:
  default:
    - step:
        name: Build and package
        script:
          - apt-get update && apt-get install -y zip
          - apt-get install -y python3-pip 
          - pip3 install -r requirements.txt --target ./package
          - cd package
          - zip -r9 ${OLDPWD}/melget.zip .
          - cd $OLDPWD
          - zip code.zip *.py
        artifacts:
          - code.zip
    - step:
        name: Update Lambda code
        script:
          - pipe: atlassian/aws-lambda-deploy:0.2.1
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: 'us-east-1'
              FUNCTION_NAME: 'melget_auto'
              COMMAND: 'update'
              ZIP_FILE: 'code.zip'