MELGet222: 
  Type: "AWS::Lambda::Function"
  Properties: 
    Description: "This lambda is for comunicating with the Mitshubishi Melcloud API"
    Environment:
        Variables:
            MELCLOUD_USER: AQICAHjqjS+M3eHB+YXYFwA4ub0Cn0PnDnhi2Nj08EHlVXsjyAHZhthU//WX5NWX6AtxQXT9AAAAazBpBgkqhkiG9w0BBwagXDBaAgEAMFUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwSQ722HQTkqSeeG3AgEQgCiNy+znNlLyyY7ZT6uy3BbgHII7wbCtqIIRmgaSO9PDW3y9vA3w89EP
            MELCLOUD_PASS: AQICAHjqjS+M3eHB+YXYFwA4ub0Cn0PnDnhi2Nj08EHlVXsjyAHAuqIV8zBhPstfad1dmRoYAAAAcTBvBgkqhkiG9w0BBwagYjBgAgEAMFsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK48XuXv0eiQSUH9MAgEQgC5LX+L44Ebc4p0wGEmYUdQ3gBoZ+LFdu8+usCwJFjd63gvxTcKpWdH17pal3E6Y
    KmsKeyArn : "arn:aws:kms:us-east-1:686550853585:key/29f9fdff-4cc0-4fd0-a5a0-99081281484f"    
    Handler: "index.handler"
    Role: 
      Fn::GetAtt: 
        - "LambdaExecutionRole"
        - "arn:aws:iam::686550853585:role/StiesManagementLambdas"
    Code: 
      S3Bucket: "private-eu-east-fran-puerto/lambdas"
      S3Key: "Melget.zip"
    Runtime: "python3.7"
    Timeout: 25
    TracingConfig:
      Mode: "Active"
